name: Create release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      id: get-tag

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: nelonoel/branch-name@v1
    - run: echo ${BRANCH_NAME}

    - name: check main branch
      if: ${BRANCH_NAME} != 'main' && ${BRANCH_NAME} != 'master'
      run: |
        echo "${BRANCH_NAME} is not allowed"
        exit 1

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Create changelog
      run: |
        echo ${GITHUB_SHA}
        go get github.com/Songmu/ghch/cmd/ghch
        ghch --latest --format markdown > changelog.md

    - name: Create draft release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get-tag.outputs.TAG }}
        release_name: 'Release ${{ steps.get-tag.outputs.TAG }}'
        body_path: ./changelog.md
        draft: false
        prerelease: false
