name: Test

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "${github.ref}"

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Get tag
      run: |
        echo "::set-output name=TAG::`echo "${github.ref}" | awk -F'/' '{print $3}'`"
      id: get-tag

    - name: Get color
      run: echo 'The selected color is' ${steps.random-color-generator.outputs.SELECTED_COLOR}

    - name: ghch
      run: |
        go get github.com/Songmu/ghch/cmd/ghch
        ghch --next-version ${{ steps.get-tag.outputs.TAG }} --format markdown
