name: Test

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get tag
      run: |
        TAG=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        echo ::set-output name=TAG::$TAG
      id: get-tag

    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.get-tag.outputs.TAG }}

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: ghch
      run: |
        go get github.com/Songmu/ghch/cmd/ghch
        ghch --next-version ${{ steps.get-tag.outputs.TAG }} --format markdown
